spring:
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/sdn-monitor?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: XCC18535507996
  redis:
    password: XCC18535507996